name: Create Trello card for new issue

on:
  issues:
    types: [opened, reopened]
    
jobs:
  create_card:
    runs-on: ubuntu-latest
    name: Creating Trello Card
    steps:
      - name: Call trello-github-actions
        id: call-trello-github-actions
        uses: jessicazu/trello-github-actions@v1.0
        with:
          trello-action: create_card_when_issue_opened
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
          TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}
          TRELLO_LIST_ID: ${{ secrets.TRELLO_BACKLOG_LIST_ID }}
